[env]
TERM = "xterm-256color"

[font]
normal = { family = "MesloLGL Nerd Font Mono", style = "Regular" }
bold = { family = "MesloLGL Nerd Font Mono", style = "Bold" }
italic = { family = "MesloLGL Nerd Font Mono", style = "Italic" }
bold_italic = { family = "MesloLGL Nerd Font Mono", style = "Bold Italic" }
size = 12
